"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app_tk_Class.py']
APP_NAME = "MacOS Utility"
DATA_FILES = ["profiles.txt"]

OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'mutility.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Set of Utilities to change operating system features",
        'CFBundleIdentifier': "com.alptugan.macosutility",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': "Copyright © 2019, Alp Tuğan, All Rights Reserved"
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
